from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

def generate_pdf_report(results, parsed_data, output_path="Static_Analysis_Report.pdf"):
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "Static Analysis Report - Column")

    # Section: Geometry
    geo = parsed_data['geometry']
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, "1. Geometry")
    c.drawString(70, height - 120, f"Height: {geo['height_m']} m")
    c.drawString(70, height - 140, f"Size: {geo['size_m']} m")

    # Section: Load
    load = parsed_data['load']
    c.drawString(50, height - 180, "2. Load")
    c.drawString(70, height - 200, f"Type: {load['type']}")
    c.drawString(70, height - 220, f"Magnitude: {load['magnitude_N']} N")

    # Section: Results
    c.drawString(50, height - 260, "3. Results")
    c.drawString(70, height - 280, f"Max Displacement (Z): {results['max_displacement_z']:.6f} m")
    # c.drawString(70, height - 300, f"Max von Mises Stress: {results['max_stress_eqv']:.2f} Pa")

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Generated by Statik Agent")

    c.showPage()
    c.save()
    print(f"✅ PDF report saved to: {output_path}")
